---
#######################################
# Configure K3s Registry Settings
#######################################
- name: Configure K3s Registry on Control Plane nodes
  hosts: control
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Create K3s configuration directory
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: 0755

    - name: Deploy registries.yaml configuration
      copy:
        src: files/registries.yaml
        dest: /etc/rancher/k3s/registries.yaml
        mode: 0644
      notify:
        - Restart k3s server

  handlers:
    - name: Restart k3s server
      service:
        name: k3s
        state: restarted

#######################################
# Configure K3s Registry on Worker nodes
#######################################
- name: Configure K3s Registry on Worker nodes
  hosts: worker
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Create K3s configuration directory
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: 0755

    - name: Deploy registries.yaml configuration
      copy:
        src: files/registries.yaml
        dest: /etc/rancher/k3s/registries.yaml
        mode: 0644
      notify:
        - Restart k3s agent

  handlers:
    - name: Restart k3s agent
      service:
        name: k3s-agent
        state: restarted