
#####################
# Configuring HA Poxy
#####################
- name: Setup HAProxy
  hosts: haproxy
  become: true
  become_method: sudo
  gather_facts: true
  tasks:
    - name: set hostname
      hostname:
        name: "{{ new_hostname }}"

    - name: Run apg-get update & apt-get install nginx
      apt:
        name: nginx
        state: latest
        update_cache: true
    - name: Install the nginx stream module
      apt:
        name: libnginx-mod-stream
        state: latest

    - name: Create nginx configuration
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify:
        - Restart nginx

    - name: Start nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

#######################################
# Configuring primary control plane node
#######################################
- name: Setup Primary K3S Control Plane node
  hosts: primary
  become: true
  become_method: sudo
  gather_facts: false
  vars_files:
    - vars/nodes.yaml
    - vars/k3s.yaml
  tasks:
    - name: Set primary server hostname
      hostname:
        name: "{{ new_hostname }}"

    - name: Install nfs-common package
      apt:
        name: nfs-common
        state: latest
        update_cache: true

    - name: Create K3s configuration directory
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: 0755

    - name: Deploy registries.yaml configuration
      copy:
        src: files/registries.yaml
        dest: /etc/rancher/k3s/registries.yaml
        mode: 0644

    - name: install K3s master server
      shell: curl -sfL https://get.k3s.io | sh -s - server --cluster-init --node-taint CriticalAddonsOnly=true:NoExecute --tls-san {{ nodes.haproxy.ip }} --node-label "topology.kubernetes.io/zone={{ node }}" {{ install_k3s_exec }}

    - name: Fetch master token
      ansible.builtin.fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: files/node-token
        flat: yes

    - name: Add HA Proxy IP to original Kube config file
      lineinfile:
        path: /etc/rancher/k3s/k3s.yaml
        regexp: "    server: https://127.0.0.1:6443"
        line: "    server: https://{{ nodes.haproxy.ip }}:6443"
        backup: yes

    - name: Fetch Kube config file
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: files/kubeconfig-k3s
        flat: yes

    # ArgoCD installation has been moved to a separate playbook: install-argocd.yaml
    # Run: ansible-playbook -i inventory/hosts.ini install-argocd.yaml


## And now, we install the two other servers
- name: Setup K3S Control Plane nodes
  hosts: secondary
  vars_files:
    - vars/nodes.yaml
    - vars/k3s.yaml
  vars:
    token: "{{ lookup('file','files/node-token') }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ new_hostname }}"

    - name: Install nfs-common package
      apt:
        name: nfs-common
        state: latest
        update_cache: true

    - name: Create K3s configuration directory
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: 0755

    - name: Deploy registries.yaml configuration
      copy:
        src: files/registries.yaml
        dest: /etc/rancher/k3s/registries.yaml
        mode: 0644

    - name: Install K3s secondary control plane servers
      shell: curl -sfL https://get.k3s.io | sh -s - server  --server https://{{ nodes.haproxy.ip }}:6443 --token={{ token }} --node-taint CriticalAddonsOnly=true:NoExecute  --tls-san {{ nodes.haproxy.ip }} --node-label "topology.kubernetes.io/zone={{ node }}" {{ install_k3s_exec }}

  handlers:
    - name: Restart secondary servers
      service:
        name: k3s
        state: restarted

##########################
# Configuring worker nodes
##########################
- name: Rename hosts
  hosts: worker
  vars:
    token: "{{ lookup('file','files/node-token') }}"
  become: true
  become_method: sudo
  gather_facts: true
  vars_files:
    - vars/nodes.yaml
  tasks:
    - name: set hostnames
      hostname:
        name: "{{ new_hostname }}"

    - name: Install nfs-common package
      apt:
        name: nfs-common
        state: latest
        update_cache: true

    - name: Create K3s configuration directory
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: 0755

    - name: Deploy registries.yaml configuration
      copy:
        src: files/registries.yaml
        dest: /etc/rancher/k3s/registries.yaml
        mode: 0644

    - name: Install K3s worker
      shell: curl -sfL https://get.k3s.io | K3S_URL=https://{{ nginx_ip}}:6443 K3S_TOKEN={{ token }} sh -s - --node-label "topology.kubernetes.io/zone={{ node }}"
